CREATE TABLE QUESTAO(
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
TITULO TEXT(500),
ID_QUIZ INTEGER,

FOREIGN KEY (ID_QUIZ) REFERENCES QUIZ (ID)
);

CREATE TABLE ALTERNATIVA(
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
NUMERO INTEGER,
CERTA INTEGER,
CORPO TEXT(200),
ID_QUESTAO INTEGER,

FOREIGN KEY (ID_QUESTAO) REFERENCES QUESTAO (ID)
);

CREATE TABLE USER(
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
NICK_NAME TEXT(100),
SENHA TEXT(100)
);

CREATE TABLE QUIZ(
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
TEMA TEXT(100),
TITULO TEXT(100)
);

CREATE TABLE GAME(
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
SCORE INTEGER,
ID_QUIZ INTEGER NOT NULL NOT NULL,
ID_USER INTEGER NOT NULL,
RESPOSTAS TEXT(200),
DATA_REALIZACAO DATETIME,

FOREIGN KEY (ID_QUIZ) REFERENCES QUIZ (ID),
FOREIGN KEY (ID_USER) REFERENCES USER (ID)

);
